import { useState, useEffect } from 'react';

type Language = 'en' | 'pt' | 'es';

export const translations = {
  en: {
    // Navigation
    ranking: 'Ranking',
    players: 'Players',
    rounds: 'Rounds',
    live: 'Live',
    settings: 'Settings',
    
    // Ranking page
    championshipRanking: 'Championship Ranking',
    trackOverallStandings: 'Track overall player standings',
    exportData: 'Export Data',
    position: 'Position',
    player: 'Player',
    points: 'Points',
    rounds_played: 'Rounds',
    bestPosition: 'Best',
    average: 'Average',
    noPlayersYet: 'No players yet',
    finalTablePrize: 'Final Table Prize Pool',
    
    // Players page
    managePlayers: 'Manage championship participants',
    addPlayer: 'Add Player',
    newPlayer: 'New Player',
    editPlayer: 'Edit Player',
    playerName: 'Player Name',
    enterName: 'Enter name...',
    add: 'Add',
    save: 'Save',
    cancel: 'Cancel',
    confirmDelete: 'Are you sure you want to delete this player?',
    noPlayersRegistered: 'No players registered yet',
    
    // Rounds page
    configureRounds: 'Configure championship rounds',
    newRound: 'New Round',
    roundNumber: 'Round Number',
    date: 'Date',
    roundType: 'Round Type',
    regular: 'Regular',
    upToRebuys: 'Up to 2 rebuys',
    freezeout: 'Freeze Out',
    noRebuy: 'No rebuy',
    knockout: 'Knockout',
    bountyPerElimination: 'Bounty per elimination',
    buyIn: 'Buy-in',
    rebuy: 'Rebuy',
    notes: 'Notes',
    optional: 'optional',
    addNotes: 'Add notes about this round...',
    participatingPlayers: 'Participating Players',
    playersSelected: 'players selected',
    playerSelected: 'player selected',
    createRound: 'Create Round',
    completedRounds: 'Completed Rounds',
    confirmDeleteRound: 'Are you sure you want to delete this round?',
    noCompletedRounds: 'No completed rounds yet',
    rebuys: 'Rebuys',
    inProgress: 'In Progress',
    accessLive: 'Access the "Live" tab to track and control this round',
    
    // Live game page
    liveGame: 'Live Game',
    noActiveRound: 'No active round at the moment',
    createNewRound: 'Create a new round in the "Rounds" tab to start',
    goToRounds: 'Go to Rounds',
    startGame: 'Start Game',
    continue: 'Continue',
    pause: 'Pause',
    finishRound: 'Finish Round',
    level: 'Level',
    next: 'Next',
    breakIn: 'break in',
    min: 'min',
    of: 'of',
    playersRemaining: 'players remaining',
    previousLevel: 'Previous Level',
    nextLevel: 'Next Level',
    lastMinute: 'Last minute!',
    clickStart: 'Click "Start Game" to begin the timer',
    activePlayers: 'Active Players',
    allPlayersEliminated: 'All players eliminated',
    finalClassification: 'Final Classification',
    restore: 'Restore',
    playerEliminated: 'Player Eliminated',
    rebuysSoFar: 'Rebuys so far',
    knockoutEarnings: 'Knockout Earnings',
    makeRebuy: 'Make Rebuy and Continue',
    confirmElimination: 'Confirm Elimination',
    stillActive: 'There are still',
    finishAnyway: 'active players. Do you want to finish anyway?',
    confirmFinish: 'Are you sure you want to finish this round? Positions will be saved and cannot be changed.',
    roundFinished: 'Round finished successfully!',
    
    // Settings page
    configureChampionship: 'Configure championship and scoring rules',
    prizeSettings: 'Prize Settings',
    defaultBuyIn: 'Default Buy-in',
    finalTablePercentage: '% for Final Table',
    totalRounds: 'Total Rounds in Championship',
    topPlayers: 'Top Players for Final Table',
    prizeDistribution: 'Prize Distribution per Round (%)',
    firstPlace: '1st Place',
    secondPlace: '2nd Place',
    thirdPlace: '3rd Place',
    total: 'Total',
    remaining: 'remaining goes to final table',
    tournamentStructure: 'Tournament Structure',
    blindLevelDuration: 'Blind Level Duration',
    perLevel: 'per level',
    blindLevels: 'Blind Levels',
    blindLevelsDescription: 'Enter blind values separated by commas. Use "BREAK" or "INTERVALO" for breaks.',
    example: 'Example',
    preview: 'Preview of Levels',
    scoringByPosition: 'Scoring by Position',
    addPosition: 'Add Position',
    scoringDescription: 'Define how many points each position receives. From 13th position onwards, all receive 5 participation points.',
    place: 'place',
    pts: 'pts',
    aboutSystem: 'About the System',
    howItWorks: 'How It Works',
    prizeSystem: 'Prize System',
    tiebreakCriteria: 'Tiebreak Criteria',
    
    // Common
    loading: 'Loading...',
    error: 'Error loading',
    interval: 'BREAK',
  },
  pt: {
    // Navigation
    ranking: 'Ranking',
    players: 'Jogadores',
    rounds: 'Rodadas',
    live: 'Ao Vivo',
    settings: 'Configurações',
    
    // Ranking page
    championshipRanking: 'Ranking do Campeonato',
    trackOverallStandings: 'Acompanhe a classificação geral dos jogadores',
    exportData: 'Exportar Dados',
    position: 'Posição',
    player: 'Jogador',
    points: 'Pontos',
    rounds_played: 'Rodadas',
    bestPosition: 'Melhor',
    average: 'Média',
    noPlayersYet: 'Nenhum jogador ainda',
    finalTablePrize: 'Prêmio Acumulado Mesa Final',
    
    // Players page
    managePlayers: 'Gerencie os participantes do campeonato',
    addPlayer: 'Adicionar Jogador',
    newPlayer: 'Novo Jogador',
    editPlayer: 'Editar Jogador',
    playerName: 'Nome do Jogador',
    enterName: 'Digite o nome...',
    add: 'Adicionar',
    save: 'Salvar',
    cancel: 'Cancelar',
    confirmDelete: 'Tem certeza que deseja excluir este jogador?',
    noPlayersRegistered: 'Nenhum jogador cadastrado ainda',
    
    // Rounds page
    configureRounds: 'Configure as rodadas do campeonato',
    newRound: 'Nova Rodada',
    roundNumber: 'Número da Rodada',
    date: 'Data',
    roundType: 'Tipo de Rodada',
    regular: 'Regular',
    upToRebuys: 'Até 2 recompras',
    freezeout: 'Freeze Out',
    noRebuy: 'Sem recompra',
    knockout: 'Knockout',
    bountyPerElimination: 'Bounty por eliminação',
    buyIn: 'Buy-in',
    rebuy: 'Recompra',
    notes: 'Observações',
    optional: 'opcional',
    addNotes: 'Adicione observações sobre esta rodada...',
    participatingPlayers: 'Jogadores Participantes',
    playersSelected: 'jogadores selecionados',
    playerSelected: 'jogador selecionado',
    createRound: 'Criar Rodada',
    completedRounds: 'Rodadas Finalizadas',
    confirmDeleteRound: 'Tem certeza que deseja excluir esta rodada?',
    noCompletedRounds: 'Nenhuma rodada finalizada ainda',
    rebuys: 'Recompras',
    inProgress: 'Em Andamento',
    accessLive: 'Acesse a aba "Ao Vivo" para acompanhar e controlar esta rodada',
    
    // Live game page
    liveGame: 'Jogo ao Vivo',
    noActiveRound: 'Nenhuma rodada ativa no momento',
    createNewRound: 'Crie uma nova rodada na aba "Rodadas" para começar',
    goToRounds: 'Ir para Rodadas',
    startGame: 'Iniciar Jogo',
    continue: 'Continuar',
    pause: 'Pausar',
    finishRound: 'Finalizar Rodada',
    level: 'Nível',
    next: 'Próximo',
    breakIn: 'intervalo em',
    min: 'min',
    of: 'de',
    playersRemaining: 'jogadores',
    previousLevel: 'Nível Anterior',
    nextLevel: 'Próximo Nível',
    lastMinute: 'Último minuto!',
    clickStart: 'Clique em "Iniciar Jogo" para começar o cronômetro',
    activePlayers: 'Jogadores Ativos',
    allPlayersEliminated: 'Todos os jogadores foram eliminados',
    finalClassification: 'Classificação Final',
    restore: 'Restaurar',
    playerEliminated: 'Jogador Eliminado',
    rebuysSoFar: 'Recompras até agora',
    knockoutEarnings: 'Ganhos Knockout',
    makeRebuy: 'Fazer Recompra e Continuar',
    confirmElimination: 'Confirmar Eliminação',
    stillActive: 'Ainda há',
    finishAnyway: 'jogadores ativos. Deseja finalizar mesmo assim?',
    confirmFinish: 'Tem certeza que deseja finalizar esta rodada? As posições serão salvas e não poderão ser alteradas.',
    roundFinished: 'Rodada finalizada com sucesso!',
    
    // Settings page
    configureChampionship: 'Configure o campeonato e as regras de pontuação',
    prizeSettings: 'Configurações de Premiação',
    defaultBuyIn: 'Buy-in Padrão',
    finalTablePercentage: '% para Mesa Final',
    totalRounds: 'Total de Rodadas no Campeonato',
    topPlayers: 'Top Jogadores para Mesa Final',
    prizeDistribution: 'Distribuição de Prêmios por Rodada (%)',
    firstPlace: '1º Lugar',
    secondPlace: '2º Lugar',
    thirdPlace: '3º Lugar',
    total: 'Total',
    remaining: 'restante vai para mesa final',
    tournamentStructure: 'Estrutura do Torneio',
    blindLevelDuration: 'Duração dos Níveis de Blinds',
    perLevel: 'por nível',
    blindLevels: 'Níveis de Blinds',
    blindLevelsDescription: 'Digite os valores dos blinds separados por vírgula. Use "BREAK" ou "INTERVALO" para intervalos.',
    example: 'Exemplo',
    preview: 'Preview dos Níveis',
    scoringByPosition: 'Pontuação por Posição',
    addPosition: 'Adicionar Posição',
    scoringDescription: 'Defina quantos pontos cada posição receberá. A partir da 13ª posição, todos recebem 5 pontos de participação.',
    place: 'lugar',
    pts: 'pts',
    aboutSystem: 'Sobre o Sistema',
    howItWorks: 'Como Funciona',
    prizeSystem: 'Sistema de Premiação',
    tiebreakCriteria: 'Critérios de Desempate',
    
    // Common
    loading: 'Carregando...',
    error: 'Erro ao carregar',
    interval: 'INTERVALO',
  },
  es: {
    // Navigation
    ranking: 'Clasificación',
    players: 'Jugadores',
    rounds: 'Rondas',
    live: 'En Vivo',
    settings: 'Configuración',
    
    // Ranking page
    championshipRanking: 'Clasificación del Campeonato',
    trackOverallStandings: 'Sigue la clasificación general de los jugadores',
    exportData: 'Exportar Datos',
    position: 'Posición',
    player: 'Jugador',
    points: 'Puntos',
    rounds_played: 'Rondas',
    bestPosition: 'Mejor',
    average: 'Promedio',
    noPlayersYet: 'No hay jugadores todavía',
    finalTablePrize: 'Premio Acumulado Mesa Final',
    
    // Players page
    managePlayers: 'Gestiona los participantes del campeonato',
    addPlayer: 'Agregar Jugador',
    newPlayer: 'Nuevo Jugador',
    editPlayer: 'Editar Jugador',
    playerName: 'Nombre del Jugador',
    enterName: 'Ingrese el nombre...',
    add: 'Agregar',
    save: 'Guardar',
    cancel: 'Cancelar',
    confirmDelete: '¿Estás seguro de que quieres eliminar este jugador?',
    noPlayersRegistered: 'No hay jugadores registrados todavía',
    
    // Rounds page
    configureRounds: 'Configura las rondas del campeonato',
    newRound: 'Nueva Ronda',
    roundNumber: 'Número de Ronda',
    date: 'Fecha',
    roundType: 'Tipo de Ronda',
    regular: 'Regular',
    upToRebuys: 'Hasta 2 recompras',
    freezeout: 'Freeze Out',
    noRebuy: 'Sin recompra',
    knockout: 'Knockout',
    bountyPerElimination: 'Bounty por eliminación',
    buyIn: 'Buy-in',
    rebuy: 'Recompra',
    notes: 'Notas',
    optional: 'opcional',
    addNotes: 'Agrega notas sobre esta ronda...',
    participatingPlayers: 'Jugadores Participantes',
    playersSelected: 'jugadores seleccionados',
    playerSelected: 'jugador seleccionado',
    createRound: 'Crear Ronda',
    completedRounds: 'Rondas Finalizadas',
    confirmDeleteRound: '¿Estás seguro de que quieres eliminar esta ronda?',
    noCompletedRounds: 'No hay rondas finalizadas todavía',
    rebuys: 'Recompras',
    inProgress: 'En Progreso',
    accessLive: 'Accede a la pestaña "En Vivo" para seguir y controlar esta ronda',
    
    // Live game page
    liveGame: 'Juego en Vivo',
    noActiveRound: 'No hay ronda activa en este momento',
    createNewRound: 'Crea una nueva ronda en la pestaña "Rondas" para comenzar',
    goToRounds: 'Ir a Rondas',
    startGame: 'Iniciar Juego',
    continue: 'Continuar',
    pause: 'Pausar',
    finishRound: 'Finalizar Ronda',
    level: 'Nivel',
    next: 'Próximo',
    breakIn: 'descanso en',
    min: 'min',
    of: 'de',
    playersRemaining: 'jugadores',
    previousLevel: 'Nivel Anterior',
    nextLevel: 'Próximo Nivel',
    lastMinute: '¡Último minuto!',
    clickStart: 'Haz clic en "Iniciar Juego" para comenzar el cronómetro',
    activePlayers: 'Jugadores Activos',
    allPlayersEliminated: 'Todos los jugadores han sido eliminados',
    finalClassification: 'Clasificación Final',
    restore: 'Restaurar',
    playerEliminated: 'Jugador Eliminado',
    rebuysSoFar: 'Recompras hasta ahora',
    knockoutEarnings: 'Ganancias Knockout',
    makeRebuy: 'Hacer Recompra y Continuar',
    confirmElimination: 'Confirmar Eliminación',
    stillActive: 'Todavía hay',
    finishAnyway: 'jugadores activos. ¿Quieres finalizar de todos modos?',
    confirmFinish: '¿Estás seguro de que quieres finalizar esta ronda? Las posiciones se guardarán y no se podrán cambiar.',
    roundFinished: '¡Ronda finalizada con éxito!',
    
    // Settings page
    configureChampionship: 'Configura el campeonato y las reglas de puntuación',
    prizeSettings: 'Configuración de Premios',
    defaultBuyIn: 'Buy-in Predeterminado',
    finalTablePercentage: '% para Mesa Final',
    totalRounds: 'Total de Rondas en el Campeonato',
    topPlayers: 'Top Jugadores para Mesa Final',
    prizeDistribution: 'Distribución de Premios por Ronda (%)',
    firstPlace: '1er Lugar',
    secondPlace: '2do Lugar',
    thirdPlace: '3er Lugar',
    total: 'Total',
    remaining: 'restante va a la mesa final',
    tournamentStructure: 'Estructura del Torneo',
    blindLevelDuration: 'Duración de los Niveles de Ciegas',
    perLevel: 'por nivel',
    blindLevels: 'Niveles de Ciegas',
    blindLevelsDescription: 'Ingresa los valores de las ciegas separados por comas. Usa "BREAK" o "INTERVALO" para descansos.',
    example: 'Ejemplo',
    preview: 'Vista Previa de los Niveles',
    scoringByPosition: 'Puntuación por Posición',
    addPosition: 'Agregar Posición',
    scoringDescription: 'Define cuántos puntos recibirá cada posición. A partir de la 13ª posición, todos reciben 5 puntos de participación.',
    place: 'lugar',
    pts: 'pts',
    aboutSystem: 'Sobre el Sistema',
    howItWorks: 'Cómo Funciona',
    prizeSystem: 'Sistema de Premios',
    tiebreakCriteria: 'Criterios de Desempate',
    
    // Common
    loading: 'Cargando...',
    error: 'Error al cargar',
    interval: 'DESCANSO',
  },
};

export function useLanguage() {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const browserLang = navigator.language.toLowerCase();
    
    if (browserLang.startsWith('pt')) {
      setLanguage('pt');
    } else if (browserLang.startsWith('es')) {
      setLanguage('es');
    } else {
      setLanguage('en');
    }
  }, []);

  const t = (key: keyof typeof translations.en): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return { language, t };
}
