import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'pt' | 'es';

export const translations = {
  en: {
    // Navigation
    ranking: 'Ranking',
    players: 'Players',
    rounds: 'Rounds',
    live: 'Live',
    settings: 'Settings',

    // Ranking page
    championshipRanking: 'Championship Ranking',
    trackOverallStandings: 'Track overall player standings',
    exportData: 'Export Data',
    position: 'Position',
    player: 'Player',
    points: 'Points',
    rounds_played: 'Rounds',
    bestPosition: 'Best',
    average: 'Average',
    noPlayersYet: 'No players yet',
    finalTablePrize: 'Final Table Prize Pool',

    // Players page
    managePlayers: 'Manage championship participants',
    addPlayer: 'Add Player',
    newPlayer: 'New Player',
    editPlayer: 'Edit Player',
    playerName: 'Player Name',
    enterName: 'Enter name...',
    add: 'Add',
    save: 'Save',
    cancel: 'Cancel',
    confirmDelete: 'Are you sure you want to delete this player?',
    noPlayersRegistered: 'No players registered yet',

    // Rounds page
    configureRounds: 'Configure championship rounds',
    newRound: 'New Round',
    roundNumber: 'Round Number',
    date: 'Date',
    roundType: 'Round Type',
    regular: 'Regular',
    upToRebuys: 'Up to 2 rebuys',
    freezeout: 'Freeze Out',
    noRebuy: 'No rebuy',
    knockout: 'Knockout',
    bountyPerElimination: 'Bounty per elimination',
    buyIn: 'Buy-in',
    rebuy: 'Rebuy',
    notes: 'Notes',
    optional: 'optional',
    addNotes: 'Add notes about this round...',
    participatingPlayers: 'Participating Players',
    playersSelected: 'players selected',
    playerSelected: 'player selected',
    createRound: 'Create Round',
    completedRounds: 'Completed Rounds',
    confirmDeleteRound: 'Are you sure you want to delete this round?',
    noCompletedRounds: 'No completed rounds yet',
    rebuys: 'Rebuys',
    inProgress: 'In Progress',
    accessLive: 'Access the "Live" tab to track and control this round',

    // Live game page
    liveGame: 'Live Game',
    noActiveRound: 'No active round at the moment',
    createNewRound: 'Create a new round in the "Rounds" tab to start',
    goToRounds: 'Go to Rounds',
    startGame: 'Start Game',
    continue: 'Continue',
    pause: 'Pause',
    finishRound: 'Finish Round',
    level: 'Level',
    next: 'Next',
    breakIn: 'break in',
    min: 'min',
    of: 'of',
    playersRemaining: 'players remaining',
    previousLevel: 'Previous Level',
    nextLevel: 'Next Level',
    lastMinute: 'Last minute!',
    clickStart: 'Click "Start Game" to begin the timer',
    activePlayers: 'Active Players',
    allPlayersEliminated: 'All players eliminated',
    finalClassification: 'Final Classification',
    restore: 'Restore',
    playerEliminated: 'Player Eliminated',
    rebuysSoFar: 'Rebuys so far',
    knockoutEarnings: 'Knockout Earnings',
    makeRebuy: 'Make Rebuy and Continue',
    confirmElimination: 'Confirm Elimination',
    stillActive: 'There are still',
    finishAnyway: 'active players. Do you want to finish anyway?',
    confirmFinish: 'Are you sure you want to finish this round? Positions will be saved and cannot be changed.',
    roundFinished: 'Round finished successfully!',

    // Settings page
    configureChampionship: 'Configure championship and scoring rules',
    prizeSettings: 'Prize Settings',
    defaultBuyIn: 'Default Buy-in',
    finalTablePercentage: '% for Final Table',
    totalRounds: 'Total Rounds in Championship',
    topPlayers: 'Top Players for Final Table',
    prizeDistribution: 'Prize Distribution per Round (%)',
    firstPlace: '1st Place',
    secondPlace: '2nd Place',
    thirdPlace: '3rd Place',
    total: 'Total',
    remaining: 'remaining goes to final table',
    tournamentStructure: 'Tournament Structure',
    blindLevelDuration: 'Blind Level Duration',
    perLevel: 'per level',
    blindLevels: 'Blind Levels',
    blindLevelsDescription: 'Enter blind values separated by commas. Use "BREAK" or "INTERVALO" for breaks.',
    example: 'Example',
    preview: 'Preview of Levels',
    scoringByPosition: 'Scoring by Position',
    addPosition: 'Add Position',
    scoringDescription: 'Define how many points each position receives. From 13th position onwards, all receive 5 participation points.',
    place: 'place',
    pts: 'pts',
    aboutSystem: 'About the System',
    howItWorks: 'How It Works',
    prizeSystem: 'Sistema de Premiação',
    tiebreakCriteria: 'Critérios de Desempate',

    // Common
    loading: 'Loading...',
    error: 'Error loading',
    interval: 'BREAK',

    // TTS Announcements
    ttsLastMinute: 'Attention players, the blinds will raise in one minute',
    ttsBreakTime: 'Attention players, we are now on a break',
    ttsBlindsChanged: 'Attention players, the blinds have changed. Small blind is {small} and big blind is {big}',
    ttsTournamentStarted: 'Attention players, the tournament has started. {blindInfo}',
    ttsSmallBlind: 'Small blind',
    ttsBigBlind: 'Big blind',

    // Missing Keys
    pokerCircuit: 'Poker Circuit',
    managePokerTournaments: 'Manage your poker tournaments',
    myChampionships: 'My Championships',
    administrator: 'Administrator',
    participant: 'Participant',
    testAudio: 'Test Audio',
    accessCode: 'Access Code',
    shareCode: 'Share this code with players so they can join',
    copy: 'Copy',
    codeCopied: 'Code copied!',
    finalTableType: 'Final Table Value Type',
    percentage: 'Percentage (%)',
    fixedValue: 'Fixed Value ($)',
    discards: 'Discards (Worst Rounds)',
    discardAfterRound: 'Apply Discards After Round',
    remove: 'Remove',
    prizePool: 'Prize Pool',
    totalCollected: 'Total Collected',
    roundPrize: 'Round Prize',
    finalTable: 'Final Table',
    champion: 'Champion',
    runnerUp: 'Runner Up',
    generatedFinalTable: 'Final Table generated successfully!',
    errorGeneratingTable: 'Error generating Final Table',

    // Championship Selector / Home
    newChampionship: 'New Championship',
    createLeagueOrTournament: 'Create a new league or tournament',
    newSingleGame: 'New Single Game',
    quickTournamentDesc: 'Quick tournament (1 day, no league)',
    join: 'Join',
    enterExistingCode: 'Enter with an existing code',
    yourChampionships: 'Your Championships',
    loginToSeeChampionships: 'Login to see your championships',
    logout: 'Logout',
    back: 'Back',
    create: 'Create',
    championshipName: 'Championship Name',
    enterChampionshipName: 'Enter championship name',
    championshipCode: 'Championship Code',
    enterCode: 'Enter code',
    invalidCode: 'Invalid code',
    success: 'Success',
    championshipCreated: 'Championship created successfully!',
    championshipJoined: 'Joined championship successfully!',

    // Auth
    loginTitle: 'Access your account',
    email: 'Email',
    password: 'Password',
    login: 'Login',
    noAccount: 'Don\'t have an account?',
    registerConfig: 'Register',
    registerTitle: 'Create your account',
    name: 'Name',
    yourName: 'Your name',
    minPassword: 'Minimum 6 characters',
    alreadyHaveAccount: 'Already have an account?',
    doLogin: 'Login',
    errorLogin: 'Incorrect email or password',
    errorRegister: 'Error creating account. Email may already be registered.',

    // Table Draw
    tableDraw: 'Table Draw',
    tableDrawTitle: 'Table Draw',
    table: 'Table',
    seat: 'Seat',
    close: 'Close',

    // Version Footer
    versionFooter: 'v4.4.4 - iOS Audio Fix • Developed with ❤️ for Poker Players',

    // Ranking page additional
    accumulatedPrize: 'Accumulated Prize',
    entries: 'Entries',
    disputedByTop: 'Disputed by top {count} players',
    afterAllRounds: 'after all rounds',
    scoreByRound: 'Score by Round',
    withDiscard: 'With Discard',
    discardActive: 'Discard active: {count} worst result(s) discarded after round {round}',

    // Live page additional
    noActiveRoundMessage: 'Start a round in the Rounds page to begin the game.',
    eliminatedPlayers: 'Eliminated Players',
    timerControls: 'Timer Controls',
    prizeDistributionTitle: 'Prize Distribution',
    roundInfo: 'Round Info',

    // Settings page additional
    tournamentRules: 'Tournament Rules',
    rulesTextLabel: 'Rules Text',
    rulesAvailableToAll: 'These rules will be available for all participants to view.',
    roundCalendar: 'Round Calendar',
    registerScheduledDates: 'Register scheduled dates for future rounds.',
    addRound: 'Add Round',
    scheduledRounds: 'Scheduled Rounds',
    noScheduledRounds: 'No scheduled rounds yet.',
    dateFormat: 'Date (day/month)',
    observations: 'Observations',
    finalTableSection: 'Final Table',
    generateFinalTable: 'Generate Final Table',
    completeAllRoundsFirst: 'Complete all rounds first',
    finalTableDateLabel: 'Final Table Date',
    autoGeneratesWithTop: 'Automatically generates a special round with top {count} players from ranking.',
    tournamentAdmins: 'Tournament Administrators',
    addAdminsDescription: 'Add other administrators to help manage the tournament. Administrators can start rounds, eliminate players, and manage settings.',
    loadingMembers: 'Loading members...',
    admin: 'Admin',
    playerRole: 'Player',
    removeAdmin: 'Remove Admin',
    makeAdmin: 'Make Admin',
    onlyRegisteredPlayers: 'Only registered players appear here. Visitors who joined just to view are not listed.',
    playerManagement: 'Player Management',
    aboutTheSystem: 'About the System',
    howItWorksTitle: 'How It Works',
    howItWorksItems: 'Register players|Configure tournament structure|Configure prizes and final table|Define scoring rules|Create rounds and select players|Use Live screen to follow the game|System calculates prizes and final table|Ranking updates in real-time',
    prizeSystemTitle: 'Prize System',
    prizeSystemDesc: '{percentage}% of each buy-in goes to final table prize. Top {players} players after {rounds} rounds compete in final table. Remainder is distributed each round per defined percentages.',
    tiebreakTitle: 'Tiebreak Criteria',
    tiebreakDesc: 'In case of points tie, tiebreak is by: best position achieved, followed by number of rounds played.',
    saveSettings: 'Save Settings',
    blindLevelsDurationTitle: 'Blind Levels Duration',
    levelPreview: 'Level Preview',
    durationEditablePerLevel: 'Editable duration per level',
    tipCustomDuration: 'Tip: You can adjust duration of specific levels (e.g., reduce to 10min after break)',
    restoreDefaults: 'Restore Defaults',

    // Live page modal texts
    removePlayer: 'Remove Player',
    removePlayerConfirm: 'Are you sure you want to remove {name} from the round? This action cannot be undone.',
    finishTournament: 'Finish Tournament',
    finishSingleGameConfirm: 'Finish single game and return to main menu?',
    finishAndExit: 'Finish and Exit',
    confirmAndFinish: 'Confirm and Finish',
    eliminatedBy: 'Eliminated by',
    undoElimination: 'Undo Elimination',
    titleDispute: 'Title Dispute',
    drawTables: 'Draw Tables',
    round: 'Round',
    dealer: 'Dealer',
    sumPrizesDealer: 'Sum (Prizes + Dealer)',
    generateFinalTableConfirm: 'Are you sure you want to generate the Final Table? This will create a new round with qualified players.',
  },
  pt: {
    // Navigation
    ranking: 'Ranking',
    players: 'Jogadores',
    rounds: 'Rodadas',
    live: 'Ao Vivo',
    settings: 'Configurações',

    // Ranking page
    championshipRanking: 'Ranking do Campeonato',
    trackOverallStandings: 'Acompanhe a classificação geral dos jogadores',
    exportData: 'Exportar Dados',
    position: 'Posição',
    player: 'Jogador',
    points: 'Pontos',
    rounds_played: 'Rodadas',
    bestPosition: 'Melhor',
    average: 'Média',
    noPlayersYet: 'Nenhum jogador ainda',
    finalTablePrize: 'Prêmio Acumulado Mesa Final',

    // Players page
    managePlayers: 'Gerencie os participantes do campeonato',
    addPlayer: 'Adicionar Jogador',
    newPlayer: 'Novo Jogador',
    editPlayer: 'Editar Jogador',
    playerName: 'Nome do Jogador',
    enterName: 'Digite o nome...',
    add: 'Adicionar',
    save: 'Salvar',
    cancel: 'Cancelar',
    confirmDelete: 'Tem certeza que deseja excluir este jogador?',
    noPlayersRegistered: 'Nenhum jogador cadastrado ainda',

    // Rounds page
    configureRounds: 'Configure as rodadas do campeonato',
    newRound: 'Nova Rodada',
    roundNumber: 'Número da Rodada',
    date: 'Data',
    roundType: 'Tipo de Rodada',
    regular: 'Regular',
    upToRebuys: 'Até 2 recompras',
    freezeout: 'Freeze Out',
    noRebuy: 'Sem recompra',
    knockout: 'Knockout',
    bountyPerElimination: 'Bounty por eliminação',
    buyIn: 'Buy-in',
    rebuy: 'Recompra',
    notes: 'Observações',
    optional: 'opcional',
    addNotes: 'Adicione observações sobre esta rodada...',
    participatingPlayers: 'Jogadores Participantes',
    playersSelected: 'jogadores selecionados',
    playerSelected: 'jogador selecionado',
    createRound: 'Criar Rodada',
    completedRounds: 'Rodadas Finalizadas',
    confirmDeleteRound: 'Tem certeza que deseja excluir esta rodada?',
    noCompletedRounds: 'Nenhuma rodada finalizada ainda',
    rebuys: 'Recompras',
    inProgress: 'Em Andamento',
    accessLive: 'Acesse a aba "Ao Vivo" para acompanhar e controlar esta rodada',

    // Live game page
    liveGame: 'Jogo ao Vivo',
    noActiveRound: 'Nenhuma rodada ativa no momento',
    createNewRound: 'Crie uma nova rodada na aba "Rodadas" para começar',
    goToRounds: 'Ir para Rodadas',
    startGame: 'Iniciar Jogo',
    continue: 'Continuar',
    pause: 'Pausar',
    finishRound: 'Finalizar Rodada',
    level: 'Nível',
    next: 'Próximo',
    breakIn: 'intervalo em',
    min: 'min',
    of: 'de',
    playersRemaining: 'jogadores',
    previousLevel: 'Nível Anterior',
    nextLevel: 'Próximo Nível',
    lastMinute: 'Último minuto!',
    clickStart: 'Clique em "Iniciar Jogo" para começar o cronômetro',
    activePlayers: 'Jogadores Ativos',
    allPlayersEliminated: 'Todos os jogadores foram eliminados',
    finalClassification: 'Classificação Final',
    restore: 'Restaurar',
    playerEliminated: 'Jogador Eliminado',
    rebuysSoFar: 'Recompras até agora',
    knockoutEarnings: 'Ganhos Knockout',
    makeRebuy: 'Fazer Recompra e Continuar',
    confirmElimination: 'Confirmar Eliminação',
    stillActive: 'Ainda há',
    finishAnyway: 'jogadores ativos. Deseja finalizar mesmo assim?',
    confirmFinish: 'Tem certeza que deseja finalizar esta rodada? As posições serão salvas e não poderão ser alteradas.',
    roundFinished: 'Rodada finalizada com sucesso!',

    // Settings page
    configureChampionship: 'Configure o campeonato e as regras de pontuação',
    prizeSettings: 'Configurações de Premiação',
    defaultBuyIn: 'Buy-in Padrão',
    finalTablePercentage: '% para Mesa Final',
    totalRounds: 'Total de Rodadas no Campeonato',
    topPlayers: 'Top Jogadores para Mesa Final',
    prizeDistribution: 'Distribuição de Prêmios por Rodada (%)',
    firstPlace: '1º Lugar',
    secondPlace: '2º Lugar',
    thirdPlace: '3º Lugar',
    total: 'Total',
    remaining: 'restante vai para mesa final',
    tournamentStructure: 'Estrutura do Torneio',
    blindLevelDuration: 'Duração dos Níveis de Blinds',
    perLevel: 'por nível',
    blindLevels: 'Níveis de Blinds',
    blindLevelsDescription: 'Digite os valores dos blinds separados por vírgula. Use "BREAK" ou "INTERVALO" para intervalos.',
    example: 'Exemplo',
    preview: 'Preview dos Níveis',
    scoringByPosition: 'Pontuação por Posição',
    addPosition: 'Adicionar Posição',
    scoringDescription: 'Defina quantos pontos cada posição receberá. A partir da 13ª posição, todos recebem 5 pontos de participação.',
    place: 'lugar',
    pts: 'pts',
    aboutSystem: 'Sobre o Sistema',
    howItWorks: 'Como Funciona',
    prizeSystem: 'Sistema de Premiação',
    tiebreakCriteria: 'Critérios de Desempate',

    // Common
    loading: 'Carregando...',
    error: 'Error ao carregar',
    interval: 'INTERVALO',

    // TTS Announcements
    ttsLastMinute: 'Atenção jogadores, os blinds vão subir em um minuto',
    ttsBreakTime: 'Atenção jogadores, agora estamos num intervalo',
    ttsBlindsChanged: 'Atenção jogadores, o blind mudou. Small blind é {small} e big blind é {big}',
    ttsTournamentStarted: 'Atenção jogadores, o torneio começou. {blindInfo}',
    ttsSmallBlind: 'Small blind',
    ttsBigBlind: 'Big blind',

    // Missing Keys
    pokerCircuit: 'Poker Circuit',
    managePokerTournaments: 'Gerencie seus torneios de poker',
    myChampionships: 'Meus Campeonatos',
    administrator: 'Administrador',
    participant: 'Participante',
    testAudio: 'Testar Áudio',
    accessCode: 'Código de Acesso',
    shareCode: 'Compartilhe este código com os jogadores para que possam participar',
    copy: 'Copiar',
    codeCopied: 'Código copiado!',
    finalTableType: 'Tipo de Valor para Mesa Final',
    percentage: 'Porcentagem (%)',
    fixedValue: 'Valor Fixo ($)',
    discards: 'Descartes (Piores Rodadas)',
    discardAfterRound: 'Aplicar Descartes Após a Rodada',
    remove: 'Remover',
    prizePool: 'Prêmio Acumulado',
    totalCollected: 'Total Arrecadado',
    roundPrize: 'Premiação Rodada',
    finalTable: 'Mesa Final',
    champion: 'Campeão',
    runnerUp: 'Vice-Campeão',
    generatedFinalTable: 'Mesa Final criada com sucesso!',
    errorGeneratingTable: 'Erro ao gerar Mesa Final',

    // Championship Selector / Home
    newChampionship: 'Novo Campeonato',
    createLeagueOrTournament: 'Crie uma nova liga ou torneio',
    newSingleGame: 'Novo Jogo Único',
    quickTournamentDesc: 'Torneio rápido (1 dia, sem liga)',
    join: 'Participar',
    enterExistingCode: 'Entre com um código existente',
    yourChampionships: 'Seus Campeonatos',
    loginToSeeChampionships: 'Faça login para ver seus campeonatos',
    logout: 'Sair',
    back: 'Voltar',
    create: 'Criar',
    championshipName: 'Nome do Campeonato',
    enterChampionshipName: 'Digite o nome do campeonato',
    championshipCode: 'Código',
    enterCode: 'ABC1234',
    invalidCode: 'Código inválido',
    success: 'Sucesso',
    championshipCreated: 'Campeonato criado com sucesso!',
    championshipJoined: 'Entrou no campeonato com sucesso!',

    // Auth
    loginTitle: 'Entre na sua conta',
    email: 'Email',
    password: 'Senha',
    login: 'Entrar',
    noAccount: 'Não tem conta?',
    registerConfig: 'Cadastre-se',
    registerTitle: 'Crie sua conta',
    name: 'Nome',
    yourName: 'Seu nome',
    minPassword: 'Mínimo 6 caracteres',
    alreadyHaveAccount: 'Já tem conta?',
    doLogin: 'Faça login',
    errorLogin: 'Email ou senha incorretos',
    errorRegister: 'Erro ao criar conta. Email pode já estar cadastrado.',

    // Table Draw
    tableDraw: 'Sorteio de Mesas',
    tableDrawTitle: 'Sorteio de Mesas',
    table: 'Mesa',
    seat: 'Lugar',
    close: 'Fechar',

    // Version Footer
    versionFooter: 'v4.4.4 - iOS Audio Fix • Desenvolvido com ❤️ para Jogadores de Poker',

    // Ranking page additional
    accumulatedPrize: 'Prêmio Acumulado',
    entries: 'Entradas',
    disputedByTop: 'Disputado pelos {count} melhores',
    afterAllRounds: 'após todas as rodadas',
    scoreByRound: 'Pontuação por Rodada',
    withDiscard: 'C/ Descarte',
    discardActive: 'Descarte ativo: {count} pior(es) resultado(s) descartado(s) após rodada {round}',

    // Live page additional
    noActiveRoundMessage: 'Inicie uma rodada na página de Rodadas para começar o jogo.',
    eliminatedPlayers: 'Jogadores Eliminados',
    timerControls: 'Controles do Timer',
    prizeDistributionTitle: 'Distribuição de Prêmios',
    roundInfo: 'Info da Rodada',

    // Settings page additional
    tournamentRules: 'Regulamento do Torneio',
    rulesTextLabel: 'Texto do Regulamento',
    rulesAvailableToAll: 'Este regulamento estará disponível para consulta de todos os participantes.',
    roundCalendar: 'Calendário de Rodadas',
    registerScheduledDates: 'Registre as datas programadas para as rodadas futuras do campeonato.',
    addRound: 'Adicionar Rodada',
    scheduledRounds: 'Rodadas Programadas',
    noScheduledRounds: 'Nenhuma rodada programada ainda.',
    dateFormat: 'Data (dia/mês)',
    observations: 'Observações',
    finalTableSection: 'Mesa Final',
    generateFinalTable: 'Gerar Mesa Final',
    completeAllRoundsFirst: 'Complete todas as rodadas primeiro',
    finalTableDateLabel: 'Data da Mesa Final',
    autoGeneratesWithTop: 'Gera automaticamente uma rodada especial com os {count} melhores jogadores do ranking.',
    tournamentAdmins: 'Administradores do Torneio',
    addAdminsDescription: 'Adicione outros administradores para ajudar a gerenciar o torneio. Administradores podem iniciar rodadas, eliminar jogadores e gerenciar configurações.',
    loadingMembers: 'Carregando membros...',
    admin: 'Admin',
    playerRole: 'Jogador',
    removeAdmin: 'Remover Admin',
    makeAdmin: 'Tornar Admin',
    onlyRegisteredPlayers: 'Apenas jogadores registrados no campeonato aparecem aqui. Visitantes que entraram só para visualizar não são listados.',
    playerManagement: 'Gestão de Jogadores',
    aboutTheSystem: 'Sobre o Sistema',
    howItWorksTitle: 'Como Funciona',
    howItWorksItems: 'Cadastre os jogadores que participarão do campeonato|Configure a estrutura do torneio (níveis de blinds, intervalos e duração)|Configure os prêmios e a mesa final|Defina as regras de pontuação por posição|Crie rodadas na aba "Rodadas" e selecione os jogadores|Use a tela "Ao Vivo" para acompanhar o jogo em tempo real|O sistema calcula automaticamente os prêmios e a mesa final|O ranking é atualizado em tempo real após cada rodada',
    prizeSystemTitle: 'Sistema de Premiação',
    prizeSystemDesc: '{percentage}% de cada buy-in vai para o prêmio da mesa final. Os {players} melhores jogadores após {rounds} rodadas disputam a mesa final. O restante é distribuído em cada rodada conforme as porcentagens definidas acima.',
    tiebreakTitle: 'Critérios de Desempate',
    tiebreakDesc: 'Em caso de empate nos pontos, o desempate é feito por: melhor posição alcançada, seguido pelo número de rodadas jogadas.',
    saveSettings: 'Salvar Configurações',
    blindLevelsDurationTitle: 'Duração dos Níveis de Blinds',
    levelPreview: 'Preview dos Níveis',
    durationEditablePerLevel: 'Duração editável por nível',
    tipCustomDuration: 'Dica: Você pode ajustar a duração de níveis específicos (ex: reduzir para 10min após o intervalo)',
    restoreDefaults: 'Restaurar Padrões',

    // Live page modal texts
    removePlayer: 'Remover Jogador',
    removePlayerConfirm: 'Tem certeza que deseja remover {name} da rodada? Esta ação não pode ser desfeita.',
    finishTournament: 'Finalizar Torneio',
    finishSingleGameConfirm: 'Finalizar jogo único e voltar ao menu principal?',
    finishAndExit: 'Finalizar e Sair',
    confirmAndFinish: 'Confirmar e Finalizar',
    eliminatedBy: 'Eliminado por',
    undoElimination: 'Desfazer Eliminação',
    titleDispute: 'Disputa pelo Título',
    drawTables: 'Sortear Mesas',
    round: 'Rodada',
    dealer: 'Dealer',
    sumPrizesDealer: 'Soma (Prêmios + Dealer)',
    generateFinalTableConfirm: 'Tem certeza que deseja gerar a Mesa Final? Esta ação criará uma nova rodada com os jogadores classificados.',
  },
  es: {
    // Navigation
    ranking: 'Clasificación',
    players: 'Jugadores',
    rounds: 'Rondas',
    live: 'En Vivo',
    settings: 'Configuración',

    // Ranking page
    championshipRanking: 'Clasificación del Campeonato',
    trackOverallStandings: 'Sigue la clasificación general de los jugadores',
    exportData: 'Exportar Datos',
    position: 'Posición',
    player: 'Jugador',
    points: 'Puntos',
    rounds_played: 'Rondas',
    bestPosition: 'Mejor',
    average: 'Promedio',
    noPlayersYet: 'No hay jugadores todavía',
    finalTablePrize: 'Premio Acumulado Mesa Final',

    // Players page
    managePlayers: 'Gestiona los participantes del campeonato',
    addPlayer: 'Agregar Jugador',
    newPlayer: 'Nuevo Jugador',
    editPlayer: 'Editar Jugador',
    playerName: 'Nombre del Jugador',
    enterName: 'Ingrese el nombre...',
    add: 'Agregar',
    save: 'Guardar',
    cancel: 'Cancelar',
    confirmDelete: '¿Estás seguro de que quieres eliminar este jugador?',
    noPlayersRegistered: 'No hay jugadores registrados todavía',

    // Rounds page
    configureRounds: 'Configura las rondas del campeonato',
    newRound: 'Nueva Ronda',
    roundNumber: 'Número de Ronda',
    date: 'Fecha',
    roundType: 'Tipo de Ronda',
    regular: 'Regular',
    upToRebuys: 'Hasta 2 recompras',
    freezeout: 'Freeze Out',
    noRebuy: 'Sin recompra',
    knockout: 'Knockout',
    bountyPerElimination: 'Bounty por eliminación',
    buyIn: 'Buy-in',
    rebuy: 'Recompra',
    notes: 'Notas',
    optional: 'opcional',
    addNotes: 'Agrega notas sobre esta ronda...',
    participatingPlayers: 'Jugadores Participantes',
    playersSelected: 'jugadores seleccionados',
    playerSelected: 'jugador seleccionado',
    createRound: 'Crear Ronda',
    completedRounds: 'Rondas Finalizadas',
    confirmDeleteRound: '¿Estás seguro de que quieres eliminar esta ronda?',
    noCompletedRounds: 'No hay rondas finalizadas todavía',
    rebuys: 'Recompras',
    inProgress: 'En Progreso',
    accessLive: 'Accede a la pestaña "En Vivo" para seguir y controlar esta ronda',

    // Live game page
    liveGame: 'Juego en Vivo',
    noActiveRound: 'No hay ronda activa en este momento',
    createNewRound: 'Crea una nueva ronda en la pestaña "Rondas" para comenzar',
    goToRounds: 'Ir a Rondas',
    startGame: 'Iniciar Juego',
    continue: 'Continuar',
    pause: 'Pausar',
    finishRound: 'Finalizar Ronda',
    level: 'Nivel',
    next: 'Próximo',
    breakIn: 'descanso en',
    min: 'min',
    of: 'de',
    playersRemaining: 'jugadores',
    previousLevel: 'Nivel Anterior',
    nextLevel: 'Próximo Nivel',
    lastMinute: '¡Último minuto!',
    clickStart: 'Haz clic en "Iniciar Juego" para comenzar el cronómetro',
    activePlayers: 'Jugadores Activos',
    allPlayersEliminated: 'Todos los jugadores han sido eliminados',
    finalClassification: 'Clasificación Final',
    restore: 'Restaurar',
    playerEliminated: 'Jugador Eliminado',
    rebuysSoFar: 'Recompras hasta ahora',
    knockoutEarnings: 'Ganancias Knockout',
    makeRebuy: 'Hacer Recompra y Continuar',
    confirmElimination: 'Confirmar Eliminación',
    stillActive: 'Todavía hay',
    finishAnyway: 'jugadores activos. ¿Quieres finalizar de todos modos?',
    confirmFinish: '¿Estás seguro de que quieres finalizar esta ronda? Las posiciones se guardarán y no se podrán cambiar.',
    roundFinished: '¡Ronda finalizada con éxito!',

    // Settings page
    configureChampionship: 'Configure el campeonato y las reglas de puntuación',
    prizeSettings: 'Configuración de Premios',
    defaultBuyIn: 'Buy-in Predeterminado',
    finalTablePercentage: '% para Mesa Final',
    totalRounds: 'Total de Rondas en el Campeonato',
    topPlayers: 'Top Players para Mesa Final',
    prizeDistribution: 'Distribución de Premios por Ronda (%)',
    firstPlace: '1er Lugar',
    secondPlace: '2do Lugar',
    thirdPlace: '3er Lugar',
    total: 'Total',
    remaining: 'restante va a la mesa final',
    tournamentStructure: 'Estructura del Torneo',
    blindLevelDuration: 'Duración de los Niveles de Ciegas',
    perLevel: 'por nivel',
    blindLevels: 'Niveles de Ciegas',
    blindLevelsDescription: 'Ingresa los valores de las ciegas separados por comas. Usa "BREAK" or "INTERVALO" para descansos.',
    example: 'Ejemplo',
    preview: 'Vista Previa de los Niveles',
    scoringByPosition: 'Puntuación por Posición',
    addPosition: 'Agregar Posición',
    scoringDescription: 'Define cuántos puntos recibirá cada posición. A partir da 13ª posición, todos reciben 5 puntos de participación.',
    place: 'lugar',
    pts: 'pts',
    aboutSystem: 'Sobre el Sistema',
    howItWorks: 'Cómo Funciona',
    prizeSystem: 'Sistema de Premios',
    tiebreakCriteria: 'Criterios de Desempate',

    // Common
    loading: 'Cargando...',
    error: 'Error al cargar',
    interval: 'DESCANSO',

    // TTS Announcements
    ttsLastMinute: 'Atención jugadores, las ciegas subirán en un minuto',
    ttsBreakTime: 'Atención jugadores, ahora estamos en descanso',
    ttsBlindsChanged: 'Atención jugadores, las ciegas han cambiado. Ciega pequeña es {small} y ciega grande es {big}',
    ttsTournamentStarted: 'Atención jugadores, el torneo ha comenzado. {blindInfo}',
    ttsSmallBlind: 'Ciega pequeña',
    ttsBigBlind: 'Ciega grande',

    // Missing Keys
    pokerCircuit: 'Poker Circuit',
    managePokerTournaments: 'Gestiona tus torneos de póquer',
    myChampionships: 'Mis Campeonatos',
    administrator: 'Administrador',
    participant: 'Participante',
    testAudio: 'Probar Audio',
    accessCode: 'Código de Acceso',
    shareCode: 'Comparte este código con los jugadores para que puedan unirse',
    copy: 'Copiar',
    codeCopied: '¡Código copiado!',
    finalTableType: 'Tipo de Valor para Mesa Final',
    percentage: 'Porcentaje (%)',
    fixedValue: 'Valor Fijo ($)',
    discards: 'Descartes (Peor Ronda)',
    discardAfterRound: 'Aplicar Descartes Después de la Ronda',
    remove: 'Eliminar',
    prizePool: 'Pozo de Premios',
    totalCollected: 'Total Recaudado',
    roundPrize: 'Premio de la Ronda',
    finalTable: 'Mesa Final',
    champion: 'Campeón',
    runnerUp: 'Subcampeón',
    generatedFinalTable: '¡Mesa Final generada con éxito!',
    errorGeneratingTable: 'Error al generar Mesa Final',

    // Championship Selector / Home
    newChampionship: 'Nuevo Campeonato',
    createLeagueOrTournament: 'Crea una nueva liga o torneo',
    newSingleGame: 'Nuevo Juego Único',
    quickTournamentDesc: 'Torneo rápido (1 día, sin liga)',
    join: 'Unirse',
    enterExistingCode: 'Ingresa con un código existente',
    yourChampionships: 'Tus Campeonatos',
    loginToSeeChampionships: 'Inicia sesión para ver tus campeonatos',
    logout: 'Salir',
    back: 'Volver',
    create: 'Crear',
    championshipName: 'Nombre del Campeonato',
    enterChampionshipName: 'Ingresa el nombre del campeonato',
    championshipCode: 'Código',
    enterCode: 'ABC1234',
    invalidCode: 'Código inválido',
    success: 'Éxito',
    championshipCreated: '¡Campeonato creado con éxito!',
    championshipJoined: '¡Te uniste al campeonato con éxito!',

    // Auth
    loginTitle: 'Accede a tu cuenta',
    email: 'Email',
    password: 'Contraseña',
    login: 'Entrar',
    noAccount: '¿No tienes cuenta?',
    registerConfig: 'Regístrate',
    registerTitle: 'Crea tu cuenta',
    name: 'Nombre',
    yourName: 'Tu nombre',
    minPassword: 'Mínimo 6 caracteres',
    alreadyHaveAccount: '¿Ya tienes cuenta?',
    doLogin: 'Inicia sesión',
    errorLogin: 'Email o contraseña incorrectos',
    errorRegister: 'Error al crear cuenta. El email puede ya estar registrado.',

    // Table Draw
    tableDraw: 'Sorteo de Mesas',
    tableDrawTitle: 'Sorteo de Mesas',
    table: 'Mesa',
    seat: 'Asiento',
    close: 'Cerrar',

    // Version Footer
    versionFooter: 'v4.4.4 - iOS Audio Fix • Desarrollado con ❤️ para Jugadores de Poker',

    // Ranking page additional
    accumulatedPrize: 'Premio Acumulado',
    entries: 'Entradas',
    disputedByTop: 'Disputado por los {count} mejores',
    afterAllRounds: 'después de todas las rondas',
    scoreByRound: 'Puntuación por Ronda',
    withDiscard: 'Con Descarte',
    discardActive: 'Descarte activo: {count} peor(es) resultado(s) descartado(s) después de la ronda {round}',

    // Live page additional
    noActiveRoundMessage: 'Inicia una ronda en la página de Rondas para comenzar el juego.',
    eliminatedPlayers: 'Jugadores Eliminados',
    timerControls: 'Controles del Timer',
    prizeDistributionTitle: 'Distribución de Premios',
    roundInfo: 'Info de la Ronda',

    // Settings page additional
    tournamentRules: 'Reglamento del Torneo',
    rulesTextLabel: 'Texto del Reglamento',
    rulesAvailableToAll: 'Este reglamento estará disponible para consulta de todos los participantes.',
    roundCalendar: 'Calendario de Rondas',
    registerScheduledDates: 'Registra las fechas programadas para las rondas futuras del campeonato.',
    addRound: 'Agregar Ronda',
    scheduledRounds: 'Rondas Programadas',
    noScheduledRounds: 'No hay rondas programadas todavía.',
    dateFormat: 'Fecha (día/mes)',
    observations: 'Observaciones',
    finalTableSection: 'Mesa Final',
    generateFinalTable: 'Generar Mesa Final',
    completeAllRoundsFirst: 'Complete todas las rondas primero',
    finalTableDateLabel: 'Fecha de la Mesa Final',
    autoGeneratesWithTop: 'Genera automáticamente una ronda especial con los {count} mejores jugadores del ranking.',
    tournamentAdmins: 'Administradores del Torneo',
    addAdminsDescription: 'Agrega otros administradores para ayudar a gestionar el torneo. Los administradores pueden iniciar rondas, eliminar jugadores y gestionar configuraciones.',
    loadingMembers: 'Cargando miembros...',
    admin: 'Admin',
    playerRole: 'Jugador',
    removeAdmin: 'Quitar Admin',
    makeAdmin: 'Hacer Admin',
    onlyRegisteredPlayers: 'Solo los jugadores registrados en el campeonato aparecen aquí. Los visitantes que entraron solo para ver no están listados.',
    playerManagement: 'Gestión de Jugadores',
    aboutTheSystem: 'Sobre el Sistema',
    howItWorksTitle: 'Cómo Funciona',
    howItWorksItems: 'Registra los jugadores que participarán|Configura la estructura del torneo (niveles de ciegas, descansos y duración)|Configura los premios y la mesa final|Define las reglas de puntuación por posición|Crea rondas en la pestaña "Rondas" y selecciona los jugadores|Usa la pantalla "En Vivo" para seguir el juego en tiempo real|El sistema calcula automáticamente los premios y la mesa final|El ranking se actualiza en tiempo real después de cada ronda',
    prizeSystemTitle: 'Sistema de Premios',
    prizeSystemDesc: '{percentage}% de cada buy-in va al premio de la mesa final. Los {players} mejores jugadores después de {rounds} rondas compiten en la mesa final. El resto se distribuye cada ronda según los porcentajes definidos.',
    tiebreakTitle: 'Criterios de Desempate',
    tiebreakDesc: 'En caso de empate en puntos, el desempate es por: mejor posición alcanzada, seguido por número de rondas jugadas.',
    saveSettings: 'Guardar Configuración',
    blindLevelsDurationTitle: 'Duración de los Niveles de Ciegas',
    levelPreview: 'Vista Previa de los Niveles',
    durationEditablePerLevel: 'Duración editable por nivel',
    tipCustomDuration: 'Consejo: Puedes ajustar la duración de niveles específicos (ej: reducir a 10min después del descanso)',
    restoreDefaults: 'Restaurar Valores',

    // Live page modal texts
    removePlayer: 'Quitar Jugador',
    removePlayerConfirm: '¿Estás seguro de que quieres quitar a {name} de la ronda? Esta acción no se puede deshacer.',
    finishTournament: 'Finalizar Torneo',
    finishSingleGameConfirm: '¿Finalizar juego único y volver al menú principal?',
    finishAndExit: 'Finalizar y Salir',
    confirmAndFinish: 'Confirmar y Finalizar',
    eliminatedBy: 'Eliminado por',
    undoElimination: 'Deshacer Eliminación',
    titleDispute: 'Disputa por el Título',
    drawTables: 'Sortear Mesas',
    round: 'Ronda',
    dealer: 'Dealer',
    sumPrizesDealer: 'Suma (Premios + Dealer)',
    generateFinalTableConfirm: '¿Estás seguro de que quieres generar la Mesa Final? Esta acción creará una nueva ronda con los jugadores clasificados.',
  },
};

// Create Context
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.en) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Provider Component
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Check localStorage first
    const saved = localStorage.getItem('app_language');
    if (saved && ['en', 'pt', 'es'].includes(saved)) {
      return saved as Language;
    }
    // Then check browser language
    const browserLang = navigator.language.toLowerCase();
    if (browserLang.startsWith('pt')) return 'pt';
    if (browserLang.startsWith('es')) return 'es';
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: keyof typeof translations.en): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// Hook to consume the context
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
